#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PLUGINDIR="$SCRIPTDIR/plugins"
MODELDIR="$SCRIPTDIR/models"
export OPPT_RESOURCE_PATH=${PLUGINDIR}:${MODELDIR}:${OPPT_RESOURCE_PATH}
export GAZEBO_MODEL_PATH=${MODELDIR}:${GAZEBO_MODEL_PATH}
export GAZEBO_RESOURCE_PATH=${PLUGINDIR}:${MODELDIR}:${GAZEBO_RESOURCE_PATH}



